import { 
  Organization, 
  Project, 
  NeedItem, 
  DeviceDonation, 
  VolunteerOpportunity, 
  VolunteerProfile, 
  DonationIntent, 
  ImpactReport, 
  AuditLogEntry, 
  UserProfile 
} from './types';

export const DEMO_USERS: Record<string, UserProfile> = {
  visitor: {
    id: 'usr_visitor_01',
    name: 'Curious Visitor',
    email: 'visitor@example.com',
    role: 'visitor',
    createdAt: '2026-08-01T10:00:00Z',
  },
  donor: {
    id: 'usr_donor_01',
    name: 'Ananya Sharma',
    email: 'ananya.donor@techforkids.org',
    role: 'donor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43210',
    createdAt: '2026-06-12T09:30:00Z',
  },
  volunteer: {
    id: 'usr_vol_01',
    name: 'Rohan Mehra',
    email: 'rohan.tech@techforkids.org',
    role: 'volunteer',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98111 22334',
    createdAt: '2026-05-18T14:15:00Z',
  },
  ngo: {
    id: 'usr_ngo_01',
    name: 'Priya Sundaram (Program Director)',
    email: 'priya@brightfutures.org',
    role: 'ngo',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org_bright_futures',
    createdAt: '2026-04-10T08:00:00Z',
  },
  admin: {
    id: 'usr_admin_01',
    name: 'Antigravity Platform Lead',
    email: 'admin@techforkids.org',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-01T00:00:00Z',
  },
};

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org_bright_futures',
    slug: 'bright-futures-learning-foundation',
    name: 'Bright Futures Learning Foundation',
    tagline: 'Bridging the digital divide for children in suburban and rural community learning hubs.',
    description: 'Bright Futures Learning Foundation (Fictional Demo Organization) provides holistic educational support, after-school digital literacy programs, and vocational computing training for orphaned and vulnerable children across peri-urban communities.',
    registrationNumber: 'REG-80G-DEL-2019-9481',
    website: 'https://brightfutures.demo.ngo',
    contactPerson: 'Priya Sundaram',
    email: 'contact@brightfutures.demo.ngo',
    phone: '+91 98220 12345',
    location: 'Delhi NCR & North Region',
    areasServed: ['Peri-urban Delhi', 'Rural Haryana', 'Vocational Shelters'],
    programs: ['Community Computer Labs', 'Girls Who Code Weekends', 'Digital Safety Workshops'],
    technologyNeedsSummary: 'Refurbished Core i5 laptops, basic networking hardware, volunteer Python/Scratch mentors.',
    verificationStatus: 'verified',
    verifiedAt: '2026-02-15T11:00:00Z',
    logoUrl: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=120&auto=format&fit=crop&q=80',
    heroImageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80',
    documents: [
      { name: 'Certificate of Trust Registration', type: 'Trust Deed', verified: true },
      { name: '12A & 80G Tax Exemption Certificates', type: 'Tax Compliance', verified: true },
      { name: 'Child Safeguarding Policy V3.2', type: 'Safeguarding Framework', verified: true },
    ],
    activeProjectsCount: 2,
    studentsReached: 180,
    devicesReceived: 24,
    isFictionalDemo: true,
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'org_digital_horizons',
    slug: 'digital-horizons-initiative',
    name: 'Digital Horizons Initiative',
    tagline: 'Igniting STEM curiosity, computational thinking, and robotics in underprivileged youth.',
    description: 'Digital Horizons (Fictional Demo Organization) collaborates with community shelters and foster centers to introduce structured coding curricula, hardware electronics with Arduino/Raspberry Pi, and safe internet literacy.',
    registrationNumber: 'REG-MH-PUN-2021-3312',
    website: 'https://digitalhorizons.demo.ngo',
    contactPerson: 'Vikram Joshi',
    email: 'hello@digitalhorizons.demo.ngo',
    phone: '+91 98450 67890',
    location: 'Pune & Western Maharashtra',
    areasServed: ['Pune Urban Clusters', 'Satara Learning Outposts'],
    programs: ['STEM Robotics Workshops', 'Internet Access Sponsorships', 'Teacher Tech Enablement'],
    technologyNeedsSummary: 'Microcontrollers (Arduino/ESP32), monitors, keyboards, broadband sponsorship.',
    verificationStatus: 'verified',
    verifiedAt: '2026-03-01T14:30:00Z',
    logoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=120&auto=format&fit=crop&q=80',
    heroImageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&auto=format&fit=crop&q=80',
    documents: [
      { name: 'Society Registration Certificate', type: 'Society Act', verified: true },
      { name: 'Annual Audited Financials 2024-25', type: 'Financial Audit', verified: true },
      { name: 'Police Verification & Safeguarding Officer Declaration', type: 'Safeguarding', verified: true },
    ],
    activeProjectsCount: 2,
    studentsReached: 120,
    devicesReceived: 18,
    isFictionalDemo: true,
    createdAt: '2026-02-20T11:00:00Z',
  },
  {
    id: 'org_futuremakers',
    slug: 'futuremakers-education-trust',
    name: 'FutureMakers Education Trust',
    tagline: 'Equipping youth in transitional care homes with cyber awareness and workplace digital skills.',
    description: 'FutureMakers Education Trust (Fictional Demo Organization) focuses on older adolescents transitioning out of child-care institutions, ensuring they have practical computer literacy, resume building, and cyber hygiene skills.',
    registrationNumber: 'REG-KA-BLR-2020-7719',
    website: 'https://futuremakers.demo.ngo',
    contactPerson: 'Kavita Menon',
    email: 'reach@futuremakers.demo.ngo',
    phone: '+91 98800 54321',
    location: 'Bengaluru & Southern Karnataka',
    areasServed: ['Bengaluru Rural', 'Mysuru Foster Support Centers'],
    programs: ['Cybersecurity & Safe Internet Academy', 'Digital Workplace Readiness'],
    technologyNeedsSummary: 'Desktops, high-speed routers, volunteer web development trainers.',
    verificationStatus: 'verified',
    verifiedAt: '2026-04-10T16:00:00Z',
    logoUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=120&auto=format&fit=crop&q=80',
    heroImageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&auto=format&fit=crop&q=80',
    documents: [
      { name: 'Trust Deed & FCRA Compliance', type: 'Statutory Registration', verified: true },
      { name: 'Child Rights & Protection Affidavit', type: 'Safeguarding Framework', verified: true },
    ],
    activeProjectsCount: 1,
    studentsReached: 95,
    devicesReceived: 12,
    isFictionalDemo: true,
    createdAt: '2026-03-15T09:00:00Z',
  },
  {
    id: 'org_samarpan',
    slug: 'samarpan-child-welfare-society',
    name: 'Samarpan Child Welfare Society',
    tagline: 'Supporting foundational literacy and technology access in tribal region community schools.',
    description: 'A grassroots non-governmental organization operating in Eastern India, currently applying for verified status on TechForKids to equip 2 community learning shelters with solar-powered computer kiosks.',
    registrationNumber: 'REG-JH-RAN-2023-1102',
    website: 'https://samarpan-childwelfare.demo.ngo',
    contactPerson: 'Amitabh Soren',
    email: 'info@samarpan-childwelfare.demo.ngo',
    phone: '+91 94311 99887',
    location: 'Ranchi District, Jharkhand',
    areasServed: ['Ranchi Tribal Belt', 'Khunti Rural Classrooms'],
    programs: ['Solar Digital Classrooms', 'Foundational Tech Literacy'],
    technologyNeedsSummary: 'Solar-compatible low-power mini PCs, offline educational hard drives.',
    verificationStatus: 'under_review',
    logoUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=120&auto=format&fit=crop&q=80',
    heroImageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&auto=format&fit=crop&q=80',
    documents: [
      { name: 'State Registration Certificate', type: 'State Society Act', verified: true },
      { name: 'Physical Center Inspection Form', type: 'Verification Audit', verified: false },
    ],
    activeProjectsCount: 0,
    studentsReached: 40,
    devicesReceived: 0,
    isFictionalDemo: true,
    createdAt: '2026-08-10T12:00:00Z',
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj_lab_delhi',
    slug: 'community-computer-lab-delhi',
    title: 'Community Computer Lab for 45 Vulnerable Youth',
    tagline: 'Equipping an after-school learning center with 8 refurbished laptops and a safe internet terminal.',
    description: 'This initiative establishes a secure, supervised 8-terminal digital learning hub at the Bright Futures community center in North Delhi. Over 45 school-going children and teenagers in institutional care will gain structured access to online educational resources, typing tutorials, and homework research under trained mentor supervision.',
    whyItMatters: 'Without access to computers outside school hours, children in community care fall 3+ years behind in foundational digital literacy, restricting their career and academic opportunities.',
    whatSupportProvides: '3 more laptops to complete the 8-machine classroom, ₹8,000 for power backups and OS installations, 2 volunteer mentors for weekend coding sessions, and 1 year of high-speed broadband.',
    organizationId: 'org_bright_futures',
    organizationName: 'Bright Futures Learning Foundation',
    organizationVerified: true,
    category: 'Technology',
    region: 'North Delhi District, Delhi NCR',
    beneficiaryGroup: '45 Youth (Ages 10–17) in community care',
    targetStudents: 45,
    status: 'active',
    urgency: 'high',
    heroImageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&auto=format&fit=crop&q=80',
    goalValue: 48000,
    currentValue: 34500,
    progressPercentage: 72,
    needs: [
      {
        id: 'need_lab_laptop',
        projectId: 'proj_lab_delhi',
        projectTitle: 'Community Computer Lab for 45 Vulnerable Youth',
        organizationId: 'org_bright_futures',
        organizationName: 'Bright Futures Learning Foundation',
        title: '3 Refurbished Laptops',
        type: 'laptop',
        category: 'Technology',
        quantityRequired: 8,
        quantityFulfilled: 5,
        unit: 'Laptops',
        priority: 'high',
        purpose: 'Required for individual student coding and research stations.',
        fulfilled: false,
      },
      {
        id: 'need_lab_refurb',
        projectId: 'proj_lab_delhi',
        projectTitle: 'Community Computer Lab for 45 Vulnerable Youth',
        organizationId: 'org_bright_futures',
        organizationName: 'Bright Futures Learning Foundation',
        title: 'Hardware Refurbishment & Power Backups',
        type: 'refurbishment_fund',
        category: 'Infrastructure',
        quantityRequired: 12000,
        quantityFulfilled: 9000,
        unit: '₹',
        priority: 'high',
        purpose: 'Covers SSD upgrades, fresh battery replacements, and safe multi-plug surge protectors.',
        fulfilled: false,
      },
      {
        id: 'need_lab_mentors',
        projectId: 'proj_lab_delhi',
        projectTitle: 'Community Computer Lab for 45 Vulnerable Youth',
        organizationId: 'org_bright_futures',
        organizationName: 'Bright Futures Learning Foundation',
        title: '2 Volunteer Coding Mentors',
        type: 'mentor',
        category: 'Coding',
        quantityRequired: 2,
        quantityFulfilled: 1,
        unit: 'Mentors (2 hrs/wk)',
        priority: 'medium',
        purpose: 'Conduct Saturday morning Scratch & visual coding modules.',
        fulfilled: false,
      }
    ],
    milestones: [
      {
        id: 'ms_1',
        title: 'Classroom Wiring & Ergonomic Desk Setup',
        description: 'Secured dedicated safe room with surge protection and seating for 12 students.',
        targetDate: '2026-06-01',
        completed: true,
        completedAt: '2026-06-04',
      },
      {
        id: 'ms_2',
        title: 'First 5 Laptops Deployed & OS Installed',
        description: 'Installed Ubuntu LTS + Scratch 3 + GCompris educational suite.',
        targetDate: '2026-07-15',
        completed: true,
        completedAt: '2026-07-18',
      },
      {
        id: 'ms_3',
        title: 'Complete 8-Station Capacity & Launch Weekend Classes',
        description: 'Fulfill remaining 3 laptops and onboard 2nd volunteer mentor.',
        targetDate: '2026-10-01',
        completed: false,
      }
    ],
    updates: [
      {
        id: 'upd_1',
        projectId: 'proj_lab_delhi',
        title: '5 Laptops Configured and First Orientation Held!',
        content: 'Thanks to recent device donors and our volunteer Rohan, 5 refurbished laptops are running smooth. We conducted a test orientation with 18 students demonstrating keyboard navigation and basic text editing.',
        postedAt: '2026-08-14T11:20:00Z',
        authorName: 'Priya Sundaram (Program Director)',
        isSafeguardedChecked: true,
      }
    ],
    impactSummary: {
      studentsReached: 32,
      computersInstalled: 5,
      volunteerHoursLogged: 24,
      workshopsConducted: 6,
    },
    createdAt: '2026-05-20T10:00:00Z',
    updatedAt: '2026-08-14T11:20:00Z',
    isFictionalDemo: true,
  },
  {
    id: 'proj_python_pune',
    slug: 'weekend-python-and-robotics-pune',
    title: 'Weekend Python & Robotics Explorer Program',
    tagline: 'Teaching computational logic and hardware prototyping to 35 high school students.',
    description: 'An interactive 12-week technical workshop series introducing Python fundamentals, algorithmic problem solving, and hands-on sensor programming with Arduino kits for adolescent learners in childcare homes.',
    whyItMatters: 'Practical STEM problem-solving gives teens the confidence and technical portfolio necessary for vocational apprenticeships and higher education admissions.',
    whatSupportProvides: '5 Arduino starter kits, 2 dedicated Python software mentors, and educational workbooks for 35 participants.',
    organizationId: 'org_digital_horizons',
    organizationName: 'Digital Horizons Initiative',
    organizationVerified: true,
    category: 'STEM',
    region: 'Pune Cluster, Maharashtra',
    beneficiaryGroup: '35 High School Learners (Ages 14–18)',
    targetStudents: 35,
    status: 'active',
    urgency: 'medium',
    heroImageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200&auto=format&fit=crop&q=80',
    goalValue: 32000,
    currentValue: 28000,
    progressPercentage: 88,
    needs: [
      {
        id: 'need_pune_arduino',
        projectId: 'proj_python_pune',
        projectTitle: 'Weekend Python & Robotics Explorer Program',
        organizationId: 'org_digital_horizons',
        organizationName: 'Digital Horizons Initiative',
        title: '5 Arduino Hardware Starter Kits',
        type: 'arduino_kit',
        category: 'STEM',
        quantityRequired: 10,
        quantityFulfilled: 8,
        unit: 'Kits',
        priority: 'high',
        purpose: 'Hands-on breadboard, LED, ultrasonic sensor, and motor experiments.',
        fulfilled: false,
      },
      {
        id: 'need_pune_mentor',
        projectId: 'proj_python_pune',
        projectTitle: 'Weekend Python & Robotics Explorer Program',
        organizationId: 'org_digital_horizons',
        organizationName: 'Digital Horizons Initiative',
        title: '1 Volunteer Python Developer',
        type: 'mentor',
        category: 'Coding',
        quantityRequired: 2,
        quantityFulfilled: 2,
        unit: 'Mentors',
        priority: 'medium',
        purpose: 'Guide students through functions, loops, and building text-based terminal games.',
        fulfilled: true,
      }
    ],
    milestones: [
      {
        id: 'ms_p1',
        title: 'Curriculum & Hardware Kit Sourcing',
        description: 'Tailored 12-week open-source curriculum finalized.',
        targetDate: '2026-07-01',
        completed: true,
        completedAt: '2026-07-03',
      },
      {
        id: 'ms_p2',
        title: 'Module 1-4: Python Basics Completed',
        description: 'All 35 students successfully created interactive math calculators.',
        targetDate: '2026-08-20',
        completed: true,
        completedAt: '2026-08-22',
      },
      {
        id: 'ms_p3',
        title: 'Robotics Project Exhibition Day',
        description: 'Students present working sensor-based barrier and light tracking projects.',
        targetDate: '2026-10-15',
        completed: false,
      }
    ],
    updates: [
      {
        id: 'upd_p1',
        projectId: 'proj_python_pune',
        title: 'Mid-cohort showcase: 100% attendance across 5 weeks',
        content: 'Students have demonstrated remarkable curiosity with Python syntax and loops. Last week we tested our first LED blink code via USB serial!',
        postedAt: '2026-08-25T15:00:00Z',
        authorName: 'Vikram Joshi',
        isSafeguardedChecked: true,
      }
    ],
    impactSummary: {
      studentsReached: 35,
      computersInstalled: 8,
      volunteerHoursLogged: 36,
      workshopsConducted: 8,
    },
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-08-25T15:00:00Z',
    isFictionalDemo: true,
  },
  {
    id: 'proj_cyber_blr',
    slug: 'cyber-hygiene-and-digital-safety-academy',
    title: 'Cyber Safety & Digital Hygiene Academy',
    tagline: 'Protecting 60 young adolescents from cyberbullying, phishing, and unsafe online exposures.',
    description: 'Comprehensive digital safety seminars and interactive roleplaying modules teaching privacy settings, strong password management, social media safety, scam recognition, and ethical internet behaviors for institutionalized youth.',
    whyItMatters: 'As first-time internet users, vulnerable children are disproportionately exposed to online scams and privacy breaches. Proactive safety education ensures they navigate the digital world with vigilance.',
    whatSupportProvides: 'Interactive workbooks, 2 volunteer cybersecurity practitioners for case-study simulations, and projector support.',
    organizationId: 'org_futuremakers',
    organizationName: 'FutureMakers Education Trust',
    organizationVerified: true,
    category: 'Cybersecurity',
    region: 'Bengaluru Urban & Rural',
    beneficiaryGroup: '60 Adolescents (Ages 12–18)',
    targetStudents: 60,
    status: 'active',
    urgency: 'normal',
    heroImageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&auto=format&fit=crop&q=80',
    goalValue: 22000,
    currentValue: 18500,
    progressPercentage: 84,
    needs: [
      {
        id: 'need_cyber_mentor',
        projectId: 'proj_cyber_blr',
        projectTitle: 'Cyber Safety & Digital Hygiene Academy',
        organizationId: 'org_futuremakers',
        organizationName: 'FutureMakers Education Trust',
        title: '1 Cybersecurity Volunteer Speaker',
        type: 'mentor',
        category: 'Cybersecurity',
        quantityRequired: 2,
        quantityFulfilled: 1,
        unit: 'Instructors',
        priority: 'medium',
        purpose: 'Deliver interactive phishing detection & 2FA workshops.',
        fulfilled: false,
      },
      {
        id: 'need_cyber_books',
        projectId: 'proj_cyber_blr',
        projectTitle: 'Cyber Safety & Digital Hygiene Academy',
        organizationId: 'org_futuremakers',
        organizationName: 'FutureMakers Education Trust',
        title: '60 Cyber Hygiene Guidebooks',
        type: 'books',
        category: 'School Supplies',
        quantityRequired: 60,
        quantityFulfilled: 45,
        unit: 'Printed Guides',
        priority: 'normal' as any,
        purpose: 'Illustrated pocket guides on privacy checkups and helpline emergency contacts.',
        fulfilled: false,
      }
    ],
    milestones: [
      {
        id: 'ms_c1',
        title: 'Curriculum tailored for youth without prior tech exposure',
        description: 'Created 4 scenario-based roleplay cards on password protection.',
        targetDate: '2026-07-10',
        completed: true,
        completedAt: '2026-07-12',
      },
      {
        id: 'ms_c2',
        title: 'Workshops 1 & 2 Conducted in Bengaluru Shelters',
        description: '45 attendees successfully audited privacy settings on practice tablets.',
        targetDate: '2026-08-05',
        completed: true,
        completedAt: '2026-08-07',
      }
    ],
    updates: [],
    impactSummary: {
      studentsReached: 45,
      computersInstalled: 0,
      volunteerHoursLogged: 16,
      workshopsConducted: 4,
    },
    createdAt: '2026-06-15T09:30:00Z',
    updatedAt: '2026-08-07T12:00:00Z',
    isFictionalDemo: true,
  },
  {
    id: 'proj_connectivity_rural',
    slug: 'rural-shelter-internet-connectivity',
    title: 'High-Speed Broadband & Offline Library Server',
    tagline: 'Connecting 50 rural children to digital encyclopedias and remote video tutoring.',
    description: 'Deploying a 50Mbps optical broadband connection alongside an offline Kiwix open-source knowledge repository to eliminate connectivity dead-zones at an outlying shelter home.',
    whyItMatters: 'Frequent internet outages in rural pockets interrupt virtual tutoring sessions and study materials.',
    whatSupportProvides: '12-month broadband sponsorship, 1 high-gain router, and 1 mini-PC offline repository server.',
    organizationId: 'org_bright_futures',
    organizationName: 'Bright Futures Learning Foundation',
    organizationVerified: true,
    category: 'Internet Access',
    region: 'Rural Haryana Learning Hub',
    beneficiaryGroup: '50 Students (Ages 8–16)',
    targetStudents: 50,
    status: 'active',
    urgency: 'critical',
    heroImageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=1200&auto=format&fit=crop&q=80',
    goalValue: 26000,
    currentValue: 12000,
    progressPercentage: 46,
    needs: [
      {
        id: 'need_conn_router',
        projectId: 'proj_connectivity_rural',
        projectTitle: 'High-Speed Broadband & Offline Library Server',
        organizationId: 'org_bright_futures',
        organizationName: 'Bright Futures Learning Foundation',
        title: 'Dual-Band Wi-Fi 6 Router',
        type: 'peripherals',
        category: 'Infrastructure',
        quantityRequired: 1,
        quantityFulfilled: 0,
        unit: 'Units',
        priority: 'urgent',
        purpose: 'Provides reliable coverage across 3 study rooms.',
        fulfilled: false,
      },
      {
        id: 'need_conn_isp',
        projectId: 'proj_connectivity_rural',
        projectTitle: 'High-Speed Broadband & Offline Library Server',
        organizationId: 'org_bright_futures',
        organizationName: 'Bright Futures Learning Foundation',
        title: '1-Year High-Speed Fiber Sponsorship',
        type: 'internet_sponsorship',
        category: 'Internet Access',
        quantityRequired: 18000,
        quantityFulfilled: 9000,
        unit: '₹',
        priority: 'urgent',
        purpose: 'Direct ISP billing for 50 Mbps unlimited line.',
        fulfilled: false,
      }
    ],
    milestones: [
      {
        id: 'ms_conn_1',
        title: 'ISP Feasibility Survey Approved',
        description: 'Fiber cable routing confirmed up to the outer gate.',
        targetDate: '2026-08-01',
        completed: true,
        completedAt: '2026-08-03',
      }
    ],
    updates: [],
    impactSummary: {
      studentsReached: 0,
      computersInstalled: 0,
      volunteerHoursLogged: 4,
      workshopsConducted: 0,
    },
    createdAt: '2026-07-20T14:00:00Z',
    updatedAt: '2026-08-03T11:00:00Z',
    isFictionalDemo: true,
  }
];

export const INITIAL_NEEDS: NeedItem[] = INITIAL_PROJECTS.flatMap(p => p.needs);

export const INITIAL_DEVICES: DeviceDonation[] = [
  {
    id: 'dev_104',
    trackingCode: 'TFK-104',
    donorName: 'Ananya Sharma',
    donorEmail: 'ananya.donor@techforkids.org',
    donorPhone: '+91 98765 43210',
    deviceType: 'Laptop',
    manufacturer: 'Dell',
    model: 'Latitude 5490',
    approximateAgeYears: 4,
    condition: 'good',
    powersOn: true,
    batteryCondition: 'good',
    hasCharger: true,
    storage: '256GB SSD',
    ram: '8GB DDR4',
    os: 'Ubuntu Linux 22.04 LTS (Refurbished)',
    pickupPreference: 'courier_pickup',
    notes: 'Clean unit, light scratch on lid, webcam and mic working perfectly.',
    status: 'In Use',
    assignedOrgName: 'Bright Futures Learning Foundation',
    assignedProjectName: 'Community Computer Lab for 45 Vulnerable Youth',
    statusHistory: [
      { status: 'Submitted', timestamp: '2026-06-10T14:20:00Z', note: 'Donation request received with photos.' },
      { status: 'Approved', timestamp: '2026-06-11T09:00:00Z', note: 'Specs verified by hardware technician.' },
      { status: 'Received', timestamp: '2026-06-14T16:30:00Z', note: 'Arrived at TechForKids central hub.' },
      { status: 'Repair', timestamp: '2026-06-16T11:00:00Z', note: 'Deep cleaned, thermal paste reapplied, battery tested at 88% health.' },
      { status: 'Ready', timestamp: '2026-06-18T10:00:00Z', note: 'OS installed with educational software and locked student profile.' },
      { status: 'Assigned', timestamp: '2026-06-20T15:00:00Z', note: 'Allocated to Delhi Community Lab.' },
      { status: 'In Use', timestamp: '2026-06-25T11:00:00Z', note: 'Deployed in classroom station #3. Actively used in weekly sessions.' },
    ],
    createdAt: '2026-06-10T14:20:00Z',
  },
  {
    id: 'dev_108',
    trackingCode: 'TFK-108',
    donorName: 'Karthik Rao',
    donorEmail: 'karthik.r@techforkids.org',
    donorPhone: '+91 98440 11223',
    deviceType: 'Laptop',
    manufacturer: 'Lenovo',
    model: 'ThinkPad T480',
    approximateAgeYears: 5,
    condition: 'good',
    powersOn: true,
    batteryCondition: 'fair',
    hasCharger: true,
    storage: '512GB NVMe SSD',
    ram: '16GB DDR4',
    os: 'Windows 10 Pro / Ubuntu dual boot ready',
    pickupPreference: 'dropoff',
    notes: 'Very durable machine, keyboard in pristine condition.',
    status: 'Ready',
    assignedOrgName: 'Digital Horizons Initiative',
    assignedProjectName: 'Weekend Python & Robotics Explorer Program',
    statusHistory: [
      { status: 'Submitted', timestamp: '2026-08-01T10:15:00Z', note: 'Online submission completed.' },
      { status: 'Approved', timestamp: '2026-08-02T12:00:00Z', note: 'Approved for robotics programming track.' },
      { status: 'Received', timestamp: '2026-08-05T14:00:00Z', note: 'Drop-off verified at hub.' },
      { status: 'Repair', timestamp: '2026-08-08T11:30:00Z', note: 'BIOS diagnostics passed, fresh SSD wipe completed.' },
      { status: 'Ready', timestamp: '2026-08-10T16:00:00Z', note: 'Staged for dispatch to Pune robotics classroom.' },
    ],
    createdAt: '2026-08-01T10:15:00Z',
  },
  {
    id: 'dev_112',
    trackingCode: 'TFK-112',
    donorName: 'Siddharth Varma',
    donorEmail: 'siddharth.v@example.com',
    deviceType: 'Desktop',
    manufacturer: 'HP',
    model: 'ProDesk 400 G5 + 21" Monitor',
    approximateAgeYears: 4,
    condition: 'good',
    powersOn: true,
    batteryCondition: 'excellent',
    hasCharger: true,
    storage: '500GB SSD',
    ram: '8GB',
    os: 'Linux Mint',
    pickupPreference: 'courier_pickup',
    status: 'Inspection',
    statusHistory: [
      { status: 'Submitted', timestamp: '2026-08-28T09:00:00Z', note: 'Submission received.' },
      { status: 'Approved', timestamp: '2026-08-29T10:30:00Z', note: 'Eligible for desktop lab station.' },
      { status: 'Received', timestamp: '2026-09-02T15:00:00Z', note: 'Received at processing center.' },
      { status: 'Inspection', timestamp: '2026-09-03T11:00:00Z', note: 'Hardware bench testing in progress.' }
    ],
    createdAt: '2026-08-28T09:00:00Z',
  }
];

export const INITIAL_VOLUNTEER_OPPORTUNITIES: VolunteerOpportunity[] = [
  {
    id: 'opp_scratch_delhi',
    projectId: 'proj_lab_delhi',
    projectTitle: 'Community Computer Lab for 45 Vulnerable Youth',
    organizationName: 'Bright Futures Learning Foundation',
    roleTitle: 'Weekend Visual Coding & Scratch Mentor',
    skillsRequired: ['Scratch', 'Basic Python', 'Patience & Mentoring', 'Hindi/English'],
    hoursPerWeek: 2,
    durationWeeks: 8,
    mode: 'in_person',
    region: 'North Delhi',
    description: 'Lead weekend interactive coding workshops for students aged 10-14 creating animations, storyboards, and mini-games.',
    openings: 2,
    urgency: 'high',
  },
  {
    id: 'opp_python_pune',
    projectId: 'proj_python_pune',
    projectTitle: 'Weekend Python & Robotics Explorer Program',
    organizationName: 'Digital Horizons Initiative',
    roleTitle: 'Python Algorithms & Logic Instructor',
    skillsRequired: ['Python', 'Problem Solving', 'Data Structures Intro'],
    hoursPerWeek: 3,
    durationWeeks: 12,
    mode: 'hybrid',
    region: 'Pune, Maharashtra',
    description: 'Guide teen learners through beginner Python logic, functions, debugging, and terminal projects.',
    openings: 1,
    urgency: 'medium',
  },
  {
    id: 'opp_cyber_blr',
    projectId: 'proj_cyber_blr',
    projectTitle: 'Cyber Safety & Digital Hygiene Academy',
    organizationName: 'FutureMakers Education Trust',
    roleTitle: 'Cybersecurity Awareness Speaker',
    skillsRequired: ['Cybersecurity', 'Online Privacy', 'Public Speaking'],
    hoursPerWeek: 2,
    durationWeeks: 4,
    mode: 'online',
    region: 'Bengaluru / Remote',
    description: 'Deliver engaging real-world case simulations on identifying phishing, managing digital footprints, and social safety.',
    openings: 2,
    urgency: 'medium',
  }
];

export const INITIAL_VOLUNTEER_PROFILES: VolunteerProfile[] = [
  {
    id: 'vol_rohan_01',
    userId: 'usr_vol_01',
    name: 'Rohan Mehra',
    email: 'rohan.tech@techforkids.org',
    skills: ['Python', 'Web Development', 'Scratch', 'Computer Repair'],
    experienceYears: 4,
    availabilityHoursPerWeek: 4,
    preferredMode: 'both',
    preferredSubjects: ['Coding', 'Web Development', 'Computer Hardware'],
    preferredAgeGroup: '11–16 years',
    location: 'Delhi NCR',
    languages: ['English', 'Hindi'],
    bio: 'Software engineer passionate about making technology joyful and accessible for curious young minds.',
    safeguardingConsent: true,
    hoursVolunteered: 24,
    workshopsCompleted: 6,
    studentsReached: 32,
    applications: [
      {
        id: 'app_01',
        opportunityId: 'opp_scratch_delhi',
        projectTitle: 'Community Computer Lab for 45 Vulnerable Youth',
        organizationName: 'Bright Futures Learning Foundation',
        status: 'active',
        appliedAt: '2026-06-05T10:00:00Z',
        hoursLogged: 24,
      }
    ]
  }
];

export const INITIAL_DONATIONS: DonationIntent[] = [
  {
    id: 'don_8842',
    receiptNumber: 'TFK-DON-8842',
    donorName: 'Ananya Sharma',
    donorEmail: 'ananya.donor@techforkids.org',
    isAnonymous: false,
    projectId: 'proj_lab_delhi',
    projectTitle: 'Community Computer Lab for 45 Vulnerable Youth',
    organizationName: 'Bright Futures Learning Foundation',
    amount: 5000,
    currency: 'INR',
    allocatedNeedType: 'refurbishment_fund',
    message: 'Happy to support laptop battery refurbishments for the kids!',
    status: 'successful',
    taxExemptEligible: true,
    complianceNotice: 'Processed transparently for project-based hardware refurbishment. Partner 80G tax receipt issued.',
    createdAt: '2026-07-02T11:45:00Z',
  },
  {
    id: 'don_8890',
    receiptNumber: 'TFK-DON-8890',
    donorName: 'Anonymous Supporter',
    donorEmail: 'supporter.anon@example.com',
    isAnonymous: true,
    projectId: 'proj_python_pune',
    projectTitle: 'Weekend Python & Robotics Explorer Program',
    organizationName: 'Digital Horizons Initiative',
    amount: 10000,
    currency: 'INR',
    allocatedNeedType: 'arduino_kit',
    message: 'Keep fostering young robotics enthusiasts.',
    status: 'successful',
    taxExemptEligible: true,
    complianceNotice: 'Monetary donation allocated to hardware purchase with verified supplier receipts.',
    createdAt: '2026-08-11T16:20:00Z',
  }
];

export const INITIAL_IMPACT_REPORTS: ImpactReport[] = [
  {
    id: 'imp_rep_q1_delhi',
    projectId: 'proj_lab_delhi',
    projectTitle: 'Community Computer Lab for 45 Vulnerable Youth',
    organizationName: 'Bright Futures Learning Foundation',
    period: 'Q2 2026',
    headline: 'From 0 Working Terminals to 5 Fully Operational Stations',
    summary: 'Prior to TechForKids support, students relied on sporadic smartphone sharing. With 5 refurbished laptops and 24 volunteer hours, 32 children completed their first 20-lesson typing and digital file management curriculum.',
    beforeState: '0 computers available; children had to travel 7 km to commercial internet cafes with high costs.',
    afterState: '5 operational laptops running Linux, dedicated power surge backup, 18 weekly hours of mentor-guided lab time.',
    computersProvided: 5,
    studentsTrained: 32,
    volunteerHours: 24,
    workshopsConducted: 6,
    verifiedByAdmin: true,
    publishedAt: '2026-08-15T12:00:00Z',
  },
  {
    id: 'imp_rep_pune_term',
    projectId: 'proj_python_pune',
    projectTitle: 'Weekend Python & Robotics Explorer Program',
    organizationName: 'Digital Horizons Initiative',
    period: 'Q2 2026',
    headline: '35 High School Learners Build Interactive Hardware Systems',
    summary: 'Equipped 8 robotics stations. Students programmed ultrasonic sensors to create automated proximity alarm devices.',
    beforeState: 'Theoretical physics only; zero exposure to microcontrollers or modern IDEs.',
    afterState: '8 Arduino development kits in regular circulation; 100% of participants wrote and flashed their own C++/Python scripts.',
    computersProvided: 8,
    studentsTrained: 35,
    volunteerHours: 36,
    workshopsConducted: 8,
    verifiedByAdmin: true,
    publishedAt: '2026-08-26T10:00:00Z',
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud_1',
    actorName: 'Antigravity Platform Lead',
    actorEmail: 'admin@techforkids.org',
    actorRole: 'admin',
    action: 'ORGANIZATION_VERIFIED',
    targetType: 'organization',
    targetId: 'org_bright_futures',
    details: 'Verified 80G/12A trust registration certificates and child safeguarding policy document.',
    timestamp: '2026-02-15T11:00:00Z',
  },
  {
    id: 'aud_2',
    actorName: 'Antigravity Platform Lead',
    actorEmail: 'admin@techforkids.org',
    actorRole: 'admin',
    action: 'PROJECT_APPROVED',
    targetType: 'project',
    targetId: 'proj_lab_delhi',
    details: 'Approved project "Community Computer Lab for 45 Vulnerable Youth" with 8 laptop target.',
    timestamp: '2026-05-22T09:30:00Z',
  },
  {
    id: 'aud_3',
    actorName: 'Antigravity Platform Lead',
    actorEmail: 'admin@techforkids.org',
    actorRole: 'admin',
    action: 'DEVICE_STATUS_UPDATE',
    targetType: 'device',
    targetId: 'dev_104',
    details: 'Updated status of Dell Latitude (TFK-104) to "In Use" after confirmation from Delhi partner.',
    timestamp: '2026-06-25T11:00:00Z',
  },
  {
    id: 'aud_4',
    actorName: 'Priya Sundaram',
    actorEmail: 'priya@brightfutures.org',
    actorRole: 'ngo',
    action: 'PROJECT_UPDATE_PUBLISHED',
    targetType: 'project',
    targetId: 'proj_lab_delhi',
    details: 'Published progress update: "5 Laptops Configured and First Orientation Held!" (Passed Safeguarding checks).',
    timestamp: '2026-08-14T11:20:00Z',
  }
];
